# Generated by Django 5.0.3 on 2024-04-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_infrastructure_data_infra_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing_data',
            name='timing',
            field=models.CharField(max_length=15),
        ),
    ]
